name: Question
description: Ask about usage or rules
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask a question about the style guide.

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
      placeholder: "How do I use this rule in commit messages?"
    validations:
      required: true
